### ISSUE TITLE
Criação do objeto BrasilAPI

### ISSUE THREAD

**Issue by victorhcb** [guhcostan/brasil-api-promisse#1]
Não seria interessante criar um objeto BrasilAPI e criar módulos a partir desse objeto?
Assim, podemos separar as dependência de cada endpoint

Exemplo de utilização:

```
const cepApi = BrasilAPI.cep('v2')
const cepResult = cepApi.getCep( )
```

Outro exemplo usando endpoint para bancos:

```
const bankApi = BrasilAPI.banks('v1')

const bank = bankApi.getBank()
const allBanks = bankApi.getAllBanks()
```

**Comment by guhcostan** [comment]
Feito! Realmente ficou melhor.
